# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Company.create(name: "HubSpot", website: "https://www.hubspot.com/careers", twitter: "https://twitter.com/HubSpot" )
Company.create(name: "DocuSign", website: "https://www.docusign.com/company/careers", twitter: "https://twitter.com/DocuSign" )
Company.create(name: "Ultimate Software", website: "https://www.ultimatesoftware.com/Careers/", twitter: "https://www.twitter.com/UltimateHCM" )
Company.create(name: "Google", website: "https://careers.google.com/jobs/?src=Online%2FHouse%20Ads%2FBKWS", twitter: "https://twitter.com/lifeatgoogle" )
Company.create(name: "LinkedIn", website: "https://www.linkedin.com/company/linkedin/jobs/", twitter: "https://twitter.com/LinkedIn" )
Company.create(name: "MathWorks", website: "https://www.mathworks.com/company/jobs/opportunities.html?s_tid=hp_ff_a_careers", twitter: "https://www.twitter.com/MATLAB" )
Company.create(name: "Nvidia", website: "https://www.nvidia.com/en-us/about-nvidia/careers/", twitter: "https://twitter.com/nvidia" )
Company.create(name: "Microsoft", website: "https://careers.microsoft.com/us/en", twitter: "https://twitter.com/microsoft" )
Company.create(name: "Facebook", website: "https://www.facebook.com/careers/?ref=pf", twitter: "https://twitter.com/Facebook" )
Company.create(name: "Compass", website: "https://www.compass.com/careers/", twitter: "https://twitter.com/compass/" )
Company.create(name: "Survey Monkey", website: "https://www.surveymonkey.com/careers/", twitter: "https://twitter.com/SurveyMonkey" )
Company.create(name: "Saleforce", website: "https://www.salesforce.com/company/careers/?d=70130000000i80S", twitter: "https://twitter.com/salesforce/?d=cta-glob-footer-2" )
Company.create(name: "Kronos Incorporated", website: "https://www.kronos.com/about-us/careers", twitter: "https://twitter.com/kronosinc" )
Company.create(name: "VMware", website: "https://careers.vmware.com/main", twitter: "https://twitter.com/VMware" )
Company.create(name: "Adobe", website: "https://www.adobe.com/careers.html", twitter: "https://twitter.com/Adobe" )
Company.create(name: "Appfolio", website: "https://www.appfolioinc.com/careers", twitter: "https://twitter.com/appfolio" )
Company.create(name: "SAP", website: "https://www.sap.com/about/careers.html", twitter: "https://twitter.com/sap" )
Company.create(name: "CDW", website: "https://www.cdwjobs.com/?bid=45", twitter: "https://twitter.com/CDWCareers" )
Company.create(name: "Yardi Systems", website: "https://careers.yardi.com", twitter: "http://www.twitter.com/yardi" )
Company.create(name: "JDA Software (Blue Yonder)", website: "https://blueyonder.com/careers", twitter: "https://twitter.com/BlueYonder" )
Company.create(name: "Nextiva", website: "https://www.nextiva.com/company/careers.html", twitter: "https://twitter.com/Nextiva" )
Company.create(name: "Paycom", website: "https://www.paycomcareers.com", twitter: "https://twitter.com/paycom" )
Company.create(name: "Dell", website: "https://jobs.dell.com", twitter: "https://twitter.com/DellTech" )
Company.create(name: "Slack", website: "https://slack.com/careers", twitter: "https://twitter.com/slackhq" )
Company.create(name: "Intuit", website: "http://careers.intuit.com/", twitter: "https://twitter.com/Intuit" )
Company.create(name: "Noon", website: "https://www.noom.com/careers/jobs", twitter: "https://twitter.com/noom?lang=en" )
Company.create(name: "UST Global", website: "https://www.ust-global.com/usa_careers", twitter: "https://twitter.com/USTGlobal" )
Company.create(name: "Cisco Systems", website: "https://www.cisco.com/c/en/us/about/careers.html", twitter: "https://twitter.com/Cisco/" )
Company.create(name: "Apple", website: "https://www.apple.com/jobs/us/", twitter: "https://twitter.com/Apple" )
Company.create(name: "Epic Systems", website: "https://careers.epic.com/?utm_source=epiccomfooter&utm_campaign=tocareers" )
Company.create(name: "Intel", website: "https://www.intel.com/content/www/us/en/jobs/jobs-at-intel.html", twitter: "https://twitter.com/intel" )